Update BUILD.md
Needed to install this as well:

```
Add a few omitted necessary packages discovered while trying to get it to build on raspbian.

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /home/pi/.cache/pypoetry/virtualenvs/protect-archiver-AraIYWLV-py3.7/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wwsmigb5/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wwsmigb5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rl58mjch/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.cache/pypoetry/virtualenvs/protect-archiver-AraIYWLV-py3.7/include/site/python3.7/cffi Check the logs for full command output.
  
```